services:
  leaderboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true